# Generated by Django 3.2.13 on 2022-05-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mainphoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
